name: MCME Animations
main: com.mcme.marozzo.animations.MCMEAnimations
destription: Stop-motion animation plugin for MCME
author: Marozzo
depend: [WorldEdit]
version: 2.0.9
commands:
   anim:
      description: MCME Animations creator.
      aliases: [a, an]
      usage: /anim help to show the list of commands
      permission: MCMEAnimations.anim
      permission-message: You don't have permission to manipulate MCMEAnimations
   manage:
     desctiption: MCME Animations manager.
     aliases: [m, man]
     usage: /manage to show the list of commands
     permission: MCMEAnimations.manage
     permission-message: You don't have permission to manage MCMEAnimations files
permissions:
    MCMEAnimations.anim:
      description: animation builder permission
      default: op
    MCMEAnimations.manage:
      description: animation files manager
      default: op